resources:
  containers:
  - container: groovy-git
    image: alxsoft/groovy-git:2.5.2-jdk8
    options: --user 0:0

jobs:
- job: Update_PackageList
  container: groovy-git
  steps:
  - bash: |
      git checkout master
      git remote rm origin
      git remote add origin "https://$GIT_USER:$(GIT_TOKEN)@github.com/$GIT_USER/scoop-frontend.git"
      git config user.name $GIT_USER
      git config user.email $GIT_EMAIL
      cd ci
      git clone https://github.com/ScoopInstaller/Main.git
      git clone https://github.com/lukesampson/scoop-extras.git
      git clone https://github.com/ScoopInstaller/Versions.git
      groovy JsonMerge.groovy
      cd ../
      git add .
      git diff-index --quiet HEAD || git commit -am "Updated package listing [skip ci]" && git push origin master