name: CI

on:
  schedule:
    - cron:  0 * * * *

jobs:
  check_skip_ci:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "CI was skipped"
        
  build_pkglist:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Install Groovy
      run: |
        sudo apt-get install groovy
    - name: Deploy pkglist
      run: |
        REPO=$(echo ${{ github.repository }} | sed "s:.*/::")
        BRANCH=$(echo ${{ github.ref }} | sed "s:.*/::")
        
        git remote rm origin
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.actor }}/${REPO}.git"
        git config user.name ${{ github.actor }}
        git config user.email noreply@${{ github.actor }}.noreply.github.com
        
        cd ci
        
        git clone https://github.com/ScoopInstaller/Main.git
        git clone https://github.com/lukesampson/scoop-extras.git
        git clone https://github.com/ScoopInstaller/Versions.git
        
        groovy JsonMerge.groovy
        
        cd ../
        
        git add .
        git diff-index --quiet HEAD || git commit -am "Updated package listing [skip ci]" && git push origin HEAD:${BRANCH}
